### Проверка доступности Eureka Server
GET http://localhost:8761/

###

### Проверка доступности API Gateway
GET http://localhost:8765/actuator/health

###

### Проверка зарегистрированных сервисов через Gateway
GET http://localhost:8765/actuator/gateway/routes

###

### 1. Регистрация нового пользователя (через Gateway)
POST http://localhost:8765/users/api/users/registration
Content-Type: application/json

{
  "name": "Паша",
  "secondName": "Техник",
  "password": "11111111",
  "email": "4057163@mail.ru",
  "birthDay": "1995-05-15",
  "enabled": false,
  "roles": ["ROLE_USER"]
}



###

### 2. Подтверждение регистрации (код нужно взять из логов/письма)
POST http://localhost:8765/users/api/users/confirm-registration?code=14A472

###

### 3. Повторная отправка кода подтверждения
POST http://localhost:8765/users/api/users/resend-confirm-registration?email=4057163@mail.ru

###

### 4. Запрос на сброс пароля
POST http://localhost:8765/users/api/users/send-password-resetCode?email=4057163@mail.ru

###

### 5. Сброс пароля с кодом
POST http://localhost:8765/users/api/users/reset-password-with-code
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&code=2DFBE7&newPassword=NewPassword123!

###

### 6. Запрос на изменение email
POST http://localhost:8765/users/api/users/send-email-reset-code
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&newEmail=9197195@mai.ru

###

### 7. Подтверждение изменения email
POST http://localhost:8765/users/api/users/confirm-email-change/1?code=FBC18C

###

### 8. Изменение пароля (требует аутентификации)
PUT http://localhost:8765/users/api/users/update-user-password/1
Authorization: Basic 9197195@mail.ru NewPassword123!
Content-Type: application/x-www-form-urlencoded

newPassword=SuperNewPassword123!&currenPassword=NewPassword123!

###

### 9. Добавление аватара (multipart/form-data)
POST http://localhost:8765/users/api/users/addAvatar/1/newAvatar
Authorization: Basic Basic 4057163@mail.ru 11111111
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary--

###

### 10. Добавление нескольких фото
POST http://localhost:8765/users/api/users/addPhotos/1
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="photo2.jpg"
Content-Type: image/jpeg

< ./test-photo2.jpg
--WebAppBoundary--
--WebAppBoundary--

###

### 11. Обновление аватара
PUT http://localhost:8765/users/api/users/updateAvatar/1/2
Authorization: Basic 4057163@mail.ru 11111111

###

### 12. Удаление фото
DELETE http://localhost:8765/users/api/users/delete-photo/1/3
Authorization: Basic 4057163@mail.ru 11111111

###

### 13. Обновление ролей (для админа)
PUT http://localhost:8765/users/api/users/update-roles/1
Authorization: Basic 4057163@mail.ru 11111111
Content-Type: application/json

["ROLE_ADMIN"]

###

### 14. Повторная отправка кода для изменения email
POST http://localhost:8765/users/api/users/resend-email-resetCode?pendingEmail=newivan@example.com

###

### 15. Получение информации о текущем пользователе (требует аутентификации)// нет нормального метода пока
GET http://localhost:8765/users/api/users/current
Authorization: Basic 4057163@mail.ru 11111111
Content-Type: application/json

###
### 16.Получение всех пользователей
GET http://localhost:8765/users/api/users/get-all-users
###

### 17. Вход в систему (POST на /login с email и password)
POST http://localhost:8765/users/login
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&password=11111111

###

### 18. Проверка аутентификации через сессию (с куками)
GET http://localhost:8765/users/api/users/current
Content-Type: application/json

###

### 19. Вход с remember-me (запоминанием)
POST http://localhost:8765/users/login
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&password=11111111&remember-me=true

###

### 20. Выход из системы
POST http://localhost:8765/users/logout
Content-Type: application/json

###

### 21. Проверка защищенного эндпоинта (требует аутентификации)
GET http://localhost:8765/users/api/users/get-all-users

###
POST http://localhost:8765/users/auth/sing-in
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

> {%
    client.global.set("access_token", response.body.token);
    client.global.set("refresh_token", response.body.refreshToken);
    client.log("Access Token: " + response.body.token);
    client.log("Refresh Token: " + response.body.refreshToken);
%}

###
POST http://localhost:8765/users/auth/refresh
Content-Type: application/json

{"refreshToken":"eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk3Nzg1NzV9.1vQ8o8rds1nu7sHgt1_h1-CpgwbwnkemQgiTSLVF0CgCCjI-K5SzVE0nyeHMTP6f"}
###


### 3. Аутентификация и получение JWT токена
POST http://localhost:8765/users/auth/sing-in
Content-Type: application/json

{
  "email": "9197195@mail.ru",
  "password": "11111111"
}

> {%
    client.global.set("access_token", response.body.token);
    client.global.set("refresh_token", response.body.refreshToken);
    client.log("Access Token: " + response.body.token);
    client.log("Refresh Token: " + response.body.refreshToken);
%}

###

### 31. Проверка метода changeAccountStatus с JWT
PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Bearer {{access_token}}

###

### 32. Проверка метода getAllUsers с JWT
GET http://localhost:8765/users/api/users/get-all-users
Authorization: Bearer {{access_token}}

###

### 33. Обновление ролей пользователя на ADMIN (через JWT)
PUT http://localhost:8765/users/api/users/update-roles/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk2OTIyNDgsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNFbmFibGVkIjp0cnVlLCJhY2NvdW50Tm9uTG9ja2VkIjp0cnVlfQ.jIDHnrI_7v09ksqb770LD6s3Zseg7RFLtEw_jhz0eIORCO1siTxZSHcIpM-n79p3
Content-Type: application/json

["ROLE_USER"]

###

### 34. Добавление аватара с JWT
POST http://localhost:8765/users/api/users/addAvatar/1/newAvatar
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk4ODc4MzAsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.QpE3uivHbUDzqCjD6Jt5QASJbjIPK9FwnXYZfdlU3YZmmVG0H4_0uis80NrELcXw
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary--
###
POST http://localhost:8765/users/api/users/addPhotos/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3Njk2OTg2NjEsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.O8Pjh17UOV_YZuHE-Ks0UPW95v2BG77JQjfOid0UFy-LTtm3rrx7uK5Gkg7V_6Ev
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test-photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg

--WebAppBoundary--
--WebAppBoundary--

###
### 3.Смена статуса аккаунта
PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Basic 4057163@mail.ru 11111111
###

POST http://localhost:8765/users/auth/sing-in
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

###

PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NjkxNzUzMTZ9.8tCdXailiKR4gSE0f4UQsMfD9jFNw59iDpCPXJy8QdcAzHlU0b-MJz-8KEmDntVL

###
PUT http://localhost:8765/users/api/users/accountBlocking/1?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk0NzIyOTUsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.RFtu3RMqG_TqjIP1ppIB-jp6udmE_3XvAyJ7dOAPZq09XmYPBSdIVBX895wARu9b
###

POST http://localhost:8765/posts/api/post/createpost
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3Njk2OTQ0NTMsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.ClOzHdFrKgByG0PgGEvHP9AIOOamP7C_Z2nU-rG-x3iDHeAgqSrkaWXPmKd2dyJ7
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="description"

ЖЖЖ
--WebAppBoundary--

###
### Просмотр публичного профиля
GET http://localhost:8765/profile/api/profile/findProfile?email=9197195@mail.ru
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk4ODc4MzAsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.QpE3uivHbUDzqCjD6Jt5QASJbjIPK9FwnXYZfdlU3YZmmVG0H4_0uis80NrELcXw
Accept: application/json

###
### 2. Проверить мой профиль через Profile Service (правильный путь)
GET http://localhost:8765/profile/api/profile/my-profile?email=9197195@mail.ru
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk4ODc1NDksInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.k5QHt8IuikAUYHFdgzmwjjvlPI9TOopidL-_vHESCgTrma9Fy-iGs3pfSTGi05Kb
Accept: application/json

###
POST http://localhost:8765/posts/api/post/createpost
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="description"

Сравните две эти фотографии! На первой - моя старая аватарка, на второй - новая. Как думаете, какая лучше? Голосуйте в комментариях!
--WebAppBoundary
Content-Disposition: form-data; name="file1"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary
Content-Disposition: form-data; name="file2"; filename="test-photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg
--WebAppBoundary--

###
