### Проверка доступности Eureka Server
GET http://localhost:8761/

###

### Проверка доступности API Gateway
GET http://localhost:8765/actuator/health

###

### Проверка зарегистрированных сервисов через Gateway
GET http://localhost:8765/actuator/gateway/routes

###

### 1. Регистрация нового пользователя (через Gateway)
POST http://localhost:8765/users/api/users/registration
Content-Type: application/json

{
  "name": "ДАНЯЯЯЯЯЯЯ",
  "secondName": "мУРАКАМИИИИИИ",
  "password": "11111111",
  "email": "WEFfklslfddkssdPP@mail.ru",
  "birthDay": "1995-05-15"
}



###

### 2. Подтверждение регистрации (код нужно взять из логов/письма)
POST http://localhost:8765/users/api/users/confirm-registration?code=14A472

###

### 3. Повторная отправка кода подтверждения
POST http://localhost:8765/users/api/users/resend-confirm-registration?email=4057163@mail.ru

###

### 4. Запрос на сброс пароля
POST http://localhost:8765/users/api/users/send-password-resetCode?email=4057163@mail.ru

###

### 5. Сброс пароля с кодом
POST http://localhost:8765/users/api/users/reset-password-with-code
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&code=2DFBE7&newPassword=NewPassword123!

###

### 6. Запрос на изменение email
POST http://localhost:8765/users/api/users/send-email-reset-code
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&newEmail=9197195@mai.ru

###

### 7. Подтверждение изменения email
POST http://localhost:8765/users/api/users/confirm-email-change/1?code=FBC18C

###

### 8. Изменение пароля (требует аутентификации)
PUT http://localhost:8765/users/api/users/update-user-password/1
Authorization: Basic 9197195@mail.ru NewPassword123!
Content-Type: application/x-www-form-urlencoded

newPassword=SuperNewPassword123!&currenPassword=NewPassword123!

###

### 9. Добавление аватара (multipart/form-data)
POST http://localhost:8765/users/api/users/addAvatar/1/newAvatar
Authorization: Basic Basic 4057163@mail.ru 11111111
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary--

###

### 10. Добавление нескольких фото
POST http://localhost:8765/users/api/users/addPhotos/1
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="photo2.jpg"
Content-Type: image/jpeg

< ./test-photo2.jpg
--WebAppBoundary--
--WebAppBoundary--

###

### 11. Обновление аватара
PUT http://localhost:8765/users/api/users/updateAvatar/1/2
Authorization: Basic 4057163@mail.ru 11111111

###

### 12. Удаление фото
DELETE http://localhost:8765/users/api/users/delete-photo/1/3
Authorization: Basic 4057163@mail.ru 11111111

###

### 13. Обновление ролей (для админа)
PUT http://localhost:8765/users/api/users/update-roles/1
Authorization: Basic 4057163@mail.ru 11111111
Content-Type: application/json

["ROLE_ADMIN"]

###

### 14. Повторная отправка кода для изменения email
POST http://localhost:8765/users/api/users/resend-email-resetCode?pendingEmail=newivan@example.com

###

### 15. Получение информации о текущем пользователе (требует аутентификации)// нет нормального метода пока
GET http://localhost:8765/users/api/users/current
Authorization: Basic 4057163@mail.ru 11111111
Content-Type: application/json

###
### 16.Получение всех пользователей
GET http://localhost:8765/users/api/users/get-all-users
###

### 17. Вход в систему (POST на /login с email и password)
POST http://localhost:8765/users/login
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&password=11111111

###

### 18. Проверка аутентификации через сессию (с куками)
GET http://localhost:8765/users/api/users/current
Content-Type: application/json

###

### 19. Вход с remember-me (запоминанием)
POST http://localhost:8765/users/login
Content-Type: application/x-www-form-urlencoded

email=4057163@mail.ru&password=11111111&remember-me=true

###

### 20. Выход из системы
POST http://localhost:8765/users/logout
Content-Type: application/json

###

### 21. Проверка защищенного эндпоинта (требует аутентификации)
GET http://localhost:8765/users/api/users/get-all-users

###
POST http://localhost:8765/users/auth/sing-in
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

> {%
    client.global.set("access_token", response.body.token);
    client.global.set("refresh_token", response.body.refreshToken);
    client.log("Access Token: " + response.body.token);
    client.log("Refresh Token: " + response.body.refreshToken);
%}

###
POST http://localhost:8765/users/auth/refresh
Content-Type: application/json

{"refreshToken":"$2a$12$E1a7U74ollfDe7/CfhXMMe0Ooz7Q/uMJOCj1J.bNZk5h4ZE2eo5gO"}
###


### 3. Аутентификация и получение JWT токена
POST http://localhost:8765/users/auth/sing-in
Content-Type: application/json

{
  "email": "9197195@mail.ru",
  "password": "11111111"
}

> {%
    client.global.set("access_token", response.body.token);
    client.global.set("refresh_token", response.body.refreshToken);
    client.log("Access Token: " + response.body.token);
    client.log("Refresh Token: " + response.body.refreshToken);
%}

###

### 31. Проверка метода changeAccountStatus с JWT
PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA0NTg4NzEsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.WRIQK1r1FHkCS3-2MqwtVVj4KafeWwwaX61RaVGAKO4I4daipaaKwoJpAUIrjO_O

###
PUT http://localhost:8765/users/api/users/accountBlocking/32?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA0ODc1MjgsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.ArZdA0-GwTPMszOWGjs8O2IAipUSgmxLgBnBSt_pBgRUyAPsR-ww1m2Cuem_MUxz
###
### accountBlocking

### 32. Проверка метода getAllUsers с JWT
GET http://localhost:8765/users/api/users/get-all-users
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA1OTMyNTksInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.-MmhQWlDa17qrRZKwSkUcML4d0HR47T4cdnYi_cjhU0Ea4YPoAf6U44mP2RdDBrI

###

### 33. Обновление ролей пользователя на ADMIN (через JWT)
PUT http://localhost:8765/users/api/users/update-roles/1
Authorization: Bearer "eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA0NjAxNjAsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.bHHQmKK9WusD_sPLkjGSLYeqVZrL_vl2N1YxMCSmpButwaDcuzbliR8f3jtV7mIZ
Content-Type: application/json

["ROLE_USER"]

###

### 34. Добавление аватара с JWT
POST http://localhost:8765/users/api/users/addAvatar/2/newAvatar
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3Njk5MDQ0MDksInVzZXJJZCI6MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzRW5hYmxlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZX0.MdlLBR9vV9kUqUBFzgmQWr7MPaHnKG43cMb5i3zQ5wZqXUhyvQY1hVapHVYxkqDr
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary--
###
POST http://localhost:8765/users/api/users/addPhotos/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3Njk2OTg2NjEsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.O8Pjh17UOV_YZuHE-Ks0UPW95v2BG77JQjfOid0UFy-LTtm3rrx7uK5Gkg7V_6Ev
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test-photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg

--WebAppBoundary--
--WebAppBoundary--

###
### 3.Смена статуса аккаунта
PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Basic 4057163@mail.ru 11111111
###

POST http://localhost:8765/users/auth/sign-in
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

###

PUT http://localhost:8765/users/api/users/changeAccountStatus/1?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3NzA0NTkyNzYsInVzZXJJZCI6MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzRW5hYmxlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZX0.N3toa9UmcvPGwCJsf9AFOkRpEnQKHDvRjKZVuieQG63FrmJ2PLNqIdGDxwS84FWu

###
PUT http://localhost:8765/users/api/users/accountBlocking/1?newAccountStatus=false
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA0NjIyNTIsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.Rqh-hu9LSnGPt-qZY2okzp8oDJFiLlr0sLO-kZSy8mD4oGP3JBQL_vL9DXwyQ95f
###

POST http://localhost:8765/posts/api/post/createpost
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk5MDIyMTUsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzRW5hYmxlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZX0.MjVUlhZ8ArVw31d-5er7S2EJbL6uGjA_byKS_7aFXIoTbIDWX0HRPwDFZouTXw5A
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="description"

Пиздец
--WebAppBoundary--

###
### Просмотр публичного профиля
GET http://localhost:8765/profile/api/profile/findProfile?email=9197195@mail.ru
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA1OTIwMTYsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.HW1o_GnjfFqEJCabMx0-W0EW-kB57b8tg-lEYHTPUjKbS0TWVgsZUuZxIfmnIGa_
Accept: application/json

###
### 2. Проверить мой профиль через Profile Service (правильный путь)
GET http://localhost:8765/profile/api/profile/my-profile/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3NzA1OTM3MzEsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.1HfEUpduj2EENiqs6R4mJN6uGFs5X8PnkIj9jAf8auUJb-g-1zswuJu28LsKckIK
Accept: application/json

###
POST http://localhost:8765/posts/api/post/createpost
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="description"

Сравните две эти фотографии! На первой - моя старая аватарка, на второй - новая. Как думаете, какая лучше? Голосуйте в комментариях!
--WebAppBoundary
Content-Disposition: form-data; name="file1"; filename="test-avatar.jpg"
Content-Type: image/jpeg

< ./test-avatar.jpg
--WebAppBoundary
Content-Disposition: form-data; name="file2"; filename="test-photo1.jpg"
Content-Type: image/jpeg

< ./test-photo1.jpg
--WebAppBoundary--

###
### 1. Обновление имени пользователя (требует аутентификации и соответствия ID)
PUT http://localhost:8765/users/api/users/updateName/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MTk3MTk1QG1haWwucnUiLCJleHAiOjE3Njk5MDkyMjIsInVzZXJJZCI6MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzRW5hYmxlZCI6dHJ1ZSwiYWNjb3VudE5vbkxvY2tlZCI6dHJ1ZX0.pjoActLHpQM0XFvIIiiyJgdQGKFVNproCdiUnrDbKlyJAlf87QMWxqr-HV4MqXs6
Content-Type: application/x-www-form-urlencoded

newName=Егор

###

### 2. Обновление фамилии пользователя
PUT http://localhost:8765/users/api/users/updateSecondName/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJleHAiOjE3Njk5MDkwNjcsInVzZXJJZCI6Miwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJpc0VuYWJsZWQiOnRydWUsImFjY291bnROb25Mb2NrZWQiOnRydWV9.ZfrEVoMDZRmX-ZuQr4B7LDhdIEum6di1xpSRExbCju47TH8H-3qcnqwXx7zbPCm3
Content-Type: application/x-www-form-urlencoded

newSecondName=Сервик

###